ACB/ACB/Controllers/WEB_pages/Country_viewController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using ACB.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;

namespace ACB.Controllers.WEB_pages
{
    public class Country_viewController : Controller
    {
        
        string baseurl = "http://localhost:7499/";   // api base url
        private readonly INotyfService _notyf;
        public Country_viewController(INotyfService notyf)
        {
            _notyf = notyf;
        }
        public ActionResult Index()   // view with model binding by saravana
        {
            try
            {

                String url = baseurl + "Country/Cntry_view";
                using (var wc = new System.Net.WebClient())
                    url = wc.DownloadString(url);
                var data = JsonConvert.DeserializeObject<List<CountryViewModel>>(url);
                _notyf.Success("Showing the Country List");
                return View(data);
            }
            catch {
                _notyf.Error("Failed");
            }

            return View();
        }
        public ActionResult Multi_view()   // inner join with model binding
        {
            try
            {
                String url = baseurl + "Country/multi_join";
                using (var wc = new System.Net.WebClient())
                    url = wc.DownloadString(url);
                var data = JsonConvert.DeserializeObject<List<MultiViewModel>>(url);
                return View(data);
            }
            catch {
                _notyf.Error("Failed");
            }
            return View();
        }
        public ActionResult Create([Bind("lastname")] insert_country country)   // insert
        {
            try
            {

                if (ModelState.IsValid)
                {
                    String url = baseurl + "Country/Create?lastname=" + country.lastname;

                    using (var wc = new System.Net.WebClient())
                        url = wc.DownloadString(url);
                    var data = JsonConvert.DeserializeObject(url);
                    string data1 = Convert.ToString(data);
                    if (data1 == "1")
                    {
                        _notyf.Success("Successfully Inserted");
                    }
                    else
                    {
                        _notyf.Error("Failed");
                    }
                    return Redirect("Index");
                }
            }
            catch {
                _notyf.Error("Failed");
            }
            return View();
        }

        public ActionResult Delete(int? id)   // delete
        {
            try
            {
                if (id == null)
                {
                    return NotFound();
                }
                else
                {

                    String url = baseurl + "Country/Delete_cntry?id=" + id;

                    using (var wc = new System.Net.WebClient())
                    {
                        url = wc.DownloadString(url);
                        var data = JsonConvert.DeserializeObject(url);
                        string data1 = Convert.ToString(data);
                        if (data1 == "1")
                        {
                            _notyf.Warning("Successfully Deleted");
                        }
                        else
                        {
                            _notyf.Error("Failed");
                        }
                        return Redirect("/Country_view/Index");
                    }

                }
            }
            catch {
                _notyf.Error("Failed");
            }
            return View();
        }

        public async Task<IActionResult> Edit(int? id)  // Edit
        {
            try
            {

                if (id == null)
                {
                    return NotFound();
                }

                String url = baseurl + "Country/Details_cntry?id=" + id;
                using (var wc = new System.Net.WebClient())
                    url = wc.DownloadString(url);
                var data = JsonConvert.DeserializeObject<CountryViewModel>(url);

                _notyf.Warning("Check the value and update");
                if (url == null)
                {
                    return NotFound();
                }
                return View(data);
            }
            catch {
                _notyf.Error("Failed");
            }
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,lastname")] CountryViewModel country)   // update
        {
            try
            {
                if (id != country.id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    String url = baseurl + "Country/Update_cntry?id=" + country.id + "&lastname=" + country.lastname;

                    using (var wc = new System.Net.WebClient())
                        url = wc.DownloadString(url);
                    var data = JsonConvert.DeserializeObject(url);
                    string data1 = Convert.ToString(data);
                    if (data1 == "1")
                    {
                        _notyf.Success("Successfully Updated");
                        return Redirect("/Country_view/Index");
                    }
                    else
                    {
                        _notyf.Error("Updation Failed");
                        //  return View();
                    }

                }
            }
            catch {
                _notyf.Error("Failed");
            }
            return View();
        }

        public ActionResult Find_country(string Name)   
        {
            if (Name != null)
            {

               
                return Redirect("/Country_view/search_country?name="+Name);
            }
            else {
                Index();
            }

            return View();
        }
        public ActionResult search_country(string Name)
        {

                String url = baseurl + "Country/Details_cntry_string?name=" + Name;
                using (var wc = new System.Net.WebClient())
                    url = wc.DownloadString(url);
                var data = JsonConvert.DeserializeObject<List<CountryViewModel>>(url);

                  return View(data);
               
        }
    }
}

ACB/ACB/Views/Country_view/Create.cshtml
@model ACB.Models.insert_country
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Insert Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="lastname" class="control-label"></label>
                <input asp-for="lastname" class="form-control" />
                <span asp-validation-for="lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ACB/ACB/Views/Country_view/Edit.cshtml
@model ACB.Models.CountryViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4>Edit Country</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="lastname" class="control-label"></label>
                <input asp-for="lastname" class="form-control" />
                <span asp-validation-for="lastname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ACB/ACB/Views/Country_view/Index.cshtml
@model IEnumerable<ACB.Models.CountryViewModel>
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
Search :

@Html.TextBox("CountryName", "", new { placeholder = "Type here to search" })   @*@Html.ActionLink("Search", "Find_country", "Country_view")*@
@*<input type="button" id="btnsrch" value="Search" />*@
@*@using (Html.BeginForm("Find_country", "Country_view", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.lastname, new
    {
        @Value = "Enter Name"
    })
        @Html.ActionLink("Search", "Find_country", "Country_view")
    }*@

@*<input type="text" name="CountryName"/>@Html.ActionLink("Search", "Find_country", "Country_view")*@

<table class="table" id="all_dt">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.lastname)
            </th>

            <th> Edit/Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lastname)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    @*<a asp-action="Details" asp-route-id="@item.id">Details</a> |*@
                    <a asp-action="Delete" asp-route-id="@item.id" style="color:red" onclick="return confirm('Are you sure you want to delete Country : @item.lastname')">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="~/js/Country_index.js"></script>

ACB/ACB/Views/Country_view/Multi_view.cshtml
@model IEnumerable<ACB.Models.MultiViewModel>
@{
    ViewData["Title"] = "Inner Join";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.uname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.uname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>

        </tr>
        }
    </tbody>
</table>

ACB/ACB/Views/Country_view/search_country.cshtml
@model IEnumerable<ACB.Models.CountryViewModel>
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>Search</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
Search :

@Html.TextBox("CountryName")   @*@Html.ActionLink("Search", "Find_country", "Country_view")*@
<input type="button" id="btnsrch" value="Search" />
@*@using (Html.BeginForm("Find_country", "Country_view", FormMethod.Post))
    {
        @Html.TextBoxFor(model => model.lastname, new
    {
        @Value = "Enter Name"
    })
        @Html.ActionLink("Search", "Find_country", "Country_view")
    }*@

@*<input type="text" name="CountryName"/>@Html.ActionLink("Search", "Find_country", "Country_view")*@

<table class="table" id="all_dt">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.lastname)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lastname)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                    @*<a asp-action="Details" asp-route-id="@item.id">Details</a> |*@
                    <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>

        $(document).ready(function () {
            $("#btnsrch").click(function () {
                $.ajax(
                    {
                        type: "POST", //HTTP POST Method
                        url: "Find_country", // Controller/View
                        data: { //Passing data
                            Name: $("#CountryName").val(), //Reading text box values using Jquery

                        },
                       

                    });

            });
        });
</script>